version: 2.1
jobs:
  test:
    docker:
      - image: circleci/node:latest-browsers
    steps:
      - checkout
      - run:
          name: Install gems
          command: gem install bundler
      - run:
          name: Install dependencies
          command: bundle install
      - run:
          name: Build the static site
          command: bundle exec jekyll build
      - run:
          name: Visual Tests
          command: npx percy snapshot _site/ # snapshot built Jekyll site
workflows:
  version: 2.1.1
  build_and_test:
    jobs:
      - test
